[params.postPreview]
enable = true
# Log to console
debug = false
# Disable on mobile/touch devices (also checks hover/pointer media queries)
mobileBp = 900
# Disable on "/" and "/<lang>/" home pages
disableOnHome = true
# Disable inside this container (e.g. homepage post list)
excludeSelector = "body > div.wrapper > main > div.home"
# Hover timings
showDelay = 120
hideDelay = 220
# Crop top part of the preview by shifting iframe content up
cropTopPx = 60
# If true: load tippy/popper from unpkg CDN
# If false: use local assets/*
tippyFromCdn = true
